### ISSUE TITLE
MTR Output Problem

### ISSUE THREAD

**Issue by dogussekerci** [hybula/lookingglass#44]
The MTR output does not display after step 5. Why might this be the case for you? Note: It is the same on your demo site.

<img width="612" alt="hybula-lg" src="https://github.com/user-attachments/assets/9882fc1d-67c7-4b29-a7d7-76873418c9b0">

**Comment by dqos** [comment]
Funny one, this is caused by `---` in the PTRs used by Turk Telecom, it makes no sense to have such PTRs but I fixed it in https://github.com/hybula/lookingglass/commit/761c00740f2dca42743eeb7f1acb0cfe312b12f6

We used `---` in the backend and JavaScript to split new content, replaced it with `@@@` which will never be used in PTRs.

The Hybula looking glass is also updated.
